### PR TITLE
imported from FRAMOS packages

### PR DESCRIPTION
**Pull request by marc-hanheide**
for the new version 2.33

### CODE REVIEW

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
@nikostsagk, please test this PR locally and see if it works with the new librealsense drivers. I tried to port over all the relevant changes from the original FRAMOS packages.

So, the new librealsense2_framos is obviously now available from our Ubuntu repositories and you should try with that one and not your own build version, just to test this properly.

Please particularly check the `/tf` changes in `realsense2_framos_camera/config/multicam_config_file.yaml`, as I don't know if they are relevant for our use case.

**Comment by nikostsagk** [comment]
@marc-hanheide Does the `librealsense2_framos` pull the new `framoscamerasuite` as well?

**Comment by marc-hanheide** [comment]
> @marc-hanheide Does the `librealsense2_framos` pull the new `framoscamerasuite` as well?

Yes, it does of course!

**Review by nikostsagk — COMMENTED** [review]
1) I've tested it using the `librealsense2_framos` from the ubuntu repository. It works, but it's a but buggy as:
- weird warnings pop up:
image

- The known problem with the udev rules insists.
- The new `librealsense2_framos` or the new `realsense2_framos_camera` required to modify the `.json` file with the manual configuration of the camera as options like:
```controls-color-backlight-compensation
controls-color-brightness
controls-color-contrast
controls-color-gamma
controls-color-hue
controls-color-power-line-frequency
 controls-color-saturation
controls-color-sharpness
controls-color-white-balance-auto
controls-color-white-balance-manual
``` 
are not supported anymore (I don't think that should concern us as long as we are happy with the default camera settings).

2) I tested it having install both `librealsense2` `librealsense2_framos` `realsense2_{camera/description}` `realsense2_framos_{camera/description}` and all packages seem to work.

**Comment by marc-hanheide** [comment]
OK, these problems are unrelated I would expect? The UVC problem you had already before. The Udev problem is not really a problem, we could change it to check for the correct rules, but I don't think this is relevant. Odd that options have been removed, or have they been renamed or likewise?
If you are happy with this, then I'll merge and release?

**Comment by nikostsagk** [comment]
Yes I think that we should proceed, as the features we work on with, seem to run without problems.
I've tested it using a Framos D435e with an Intel D435i. We should try it on our 3 Framos camera configuration as this is the most important bit.

**Pull request merged**
